In [1]:
import pickle 
import numpy as np
import pandas as pd


from scipy.optimize import minimize

from nelder_mead import objective


In [ ]:

params =0.038779  , 0.004799 , 0.029957

history = []

valid_solution  = []
params = np.array(params)

def callback(x):
    fobj = objective(x)
    
    history.append(fobj)
    
    
    if fobj < 0.00434:
        valid_solution.append(x)
    
    print("---------------------------------------")
    print("Current p, I0 and alpha")
    print('{0:4f}  {1: 3.6f} {2: 3.6f}'.format( x[0], x[1], x[2]))
    #print('{0:3.6f}'.format( x[0]))
    print('Current objective')
    print(fobj)
    print("---------------------------------------")
    
    
    
res = minimize(objective, params, method='nelder-mead',
               options={'xatol': 1e-8, 'disp': True}, callback=callback)

File already exists
/cv19wifi/tmp/network_modeling/simulation_output/calibration_output/berkeley_all_2020-08-17_p:0.038779_I_asym:0.004799_alpha:0.029957_simu.pkl already exists
File already exists
/cv19wifi/tmp/network_modeling/simulation_output/calibration_output/berkeley_all_2020-08-17_p:0.04071795_I_asym:0.004799_alpha:0.029957_simu.pkl already exists
File already exists
Iter: 1
Iter: 5
Iter: 9
Iter: 13
Category: berkeley_all
Category: berkeley_all
Category: berkeley_all
/cv19wifi/tmp/network_modeling/simulation_output/usr_sets/set_118_2020-08-17_all.p
/cv19wifi/tmp/network_modeling/simulation_output/usr_sets/set_118_2020-08-17_all.p
/cv19wifi/tmp/network_modeling/simulation_output/usr_sets/set_118_2020-08-17_all.p
Category: berkeley_all
/cv19wifi/tmp/network_modeling/simulation_output/usr_sets/set_118_2020-08-17_all.p
Population size: 22401
Population size: 22401
Population size: 22401
Population size: 22401
Running step 0
Running step 0
/cv19wifi/tmp/network_modeling/coloc_proj/a

In [2]:
res.x

NameError: name 'res' is not defined

In [4]:
slns = np.unique(valid_solution, axis=0)
slns

array([[0.02697687, 0.01303429, 0.0385675 ],
       [0.02802451, 0.01277361, 0.03221521],
       [0.02884662, 0.01220879, 0.03216479],
       [0.02909548, 0.01203301, 0.03186408],
       [0.02913658, 0.01203492, 0.0317917 ],
       [0.02917767, 0.01203684, 0.03171932],
       [0.0293013 , 0.01191042, 0.03175983],
       [0.0293013 , 0.01191042, 0.03175983],
       [0.02930137, 0.01191085, 0.03175731],
       [0.02946503, 0.01251292, 0.03266894],
       [0.02966873, 0.01164397, 0.03211438]])

In [ ]:
array([[0.02940123, 0.01138308, 0.02935103],
       [0.02958333, 0.01130556, 0.02947778],
       [0.03      , 0.011     , 0.0294    ]])

array([[0.02385223, 0.00952549, 0.02614507]])


array([[0.04478056, 0.01204282, 0.03185417],
       [0.04522626, 0.01195731, 0.03151456],
       [0.0455    , 0.01166667, 0.03135   ]])

array([[0.03    , 0.011957, 0.031515]])

array([[0.02357202, 0.01064115, 0.03483618],
       [0.02769547, 0.01023282, 0.03054143],
       [0.02833333, 0.01003704, 0.02856591]])

array([[0.02697687, 0.01303429, 0.0385675 ],
       [0.02802451, 0.01277361, 0.03221521],
       [0.02966873, 0.01164397, 0.03211438]])


###
[0.037398 ,  0.010652 , 0.036342]
[0.032604 ,  0.012396 , 0.030682]
[0.034905 ,  0.011540 , 0.034525]
[0.030611 ,  0.013039  , 0.031093]
[0.034905  , 0.011540 , 0.040000]
[0.033742  , 0.011732 , 0.036000]
[0.042000  , 0.012117 , 0.036000]
[0.041481  , 0.012651 , 0.032593]
[0.043920  , 0.012874 , 0.028176]
[0.044938  , 0.012300 , 0.032412]
[0.042518  , 0.012335 , 0.033408]

In [3]:


##GT weeks 0- 4
A = np.array([[0.02940123, 0.01138308, 0.02935103],
       [0.02958333, 0.01130556, 0.02947778],
       [0.03      , 0.011     , 0.0294    ],
        [0.02385223, 0.00952549, 0.02614507],
        [0.04478056, 0.01204282, 0.03185417],
       [0.04522626, 0.01195731, 0.03151456],
       [0.0455    , 0.01166667, 0.03135   ],
         [0.03    , 0.011957, 0.031515],
        [0.02357202, 0.01064115, 0.03483618],
       [0.02769547, 0.01023282, 0.03054143],
       [0.02833333, 0.01003704, 0.02856591],
        [0.02697687, 0.01303429, 0.0385675 ],
       [0.02802451, 0.01277361, 0.03221521],
       [0.02966873, 0.01164397, 0.03211438] ,
       [0.037398 ,  0.010652 , 0.036342],
[0.032604 ,  0.012396 , 0.030682],
[0.034905 ,  0.011540 , 0.034525],
[0.030611 ,  0.013039  , 0.031093],
[0.034905  , 0.011540 , 0.040000],
[0.033742  , 0.011732 , 0.036000],
[0.042000  , 0.012117 , 0.036000],
[0.041481  , 0.012651 , 0.032593],
[0.043920  , 0.012874 , 0.028176],
[0.044938  , 0.012300 , 0.032412],
[0.042518  , 0.012335 , 0.033408]     ])


##GT weeks 5-9

0.071300   0.000620  0.003705

0.067083   0.000633  0.003770

0.074073   0.000644  0.003540

0.078608   0.000500  0.004500

0.076737   0.000512  0.004500

0.076780   0.000513  0.004528  

0.079189   0.000470  0.005274

0.079301   0.000468  0.005272

0.067968   0.000636  0.003778

0.068411   0.000638  0.003782

0.068853   0.000639  0.003786

## GT weeks 10-14


0.002157   0.002799  0.013248

0.001977   0.002078  0.016362

0.002025   0.002311  0.015877

0.002341   0.003231  0.013171

0.002493   0.002802  0.014905

0.002778   0.002205  0.016838

0.002473   0.003654  0.019977

0.002713   0.003811  0.015314

0.002626   0.003839  0.016091

0.002611   0.003880  0.016251

0.001989   0.002143  0.016464


##UIUC

0.025276   0.005815  0.004961

0.024390   0.004653  0.006181

0.025209   0.003269  0.007596

0.024578   0.002721  0.008021

0.023331   0.003118  0.007671

0.023279   0.003087  0.007723

0.026042   0.005793  0.005016

0.025975   0.005828  0.005009

0.024168   0.002857  0.007754

0.024066   0.002823  0.007988

0.024578   0.002721  0.008021

##UCB


0.036000   0.005250  0.045000

0.036409   0.005197  0.043429

0.040000   0.005000  0.046125

0.039944   0.005081  0.045729

0.042750   0.004400  0.040500

0.045000   0.004533  0.033000

0.038695   0.004803  0.030055

0.038779   0.004799  0.029957

0.044175   0.004547  0.038475

0.043014   0.004688  0.036750

0.044696   0.004749  0.034443


In [4]:
A.shape

(25, 3)

In [5]:
A

array([[0.02940123, 0.01138308, 0.02935103],
       [0.02958333, 0.01130556, 0.02947778],
       [0.03      , 0.011     , 0.0294    ],
       [0.02385223, 0.00952549, 0.02614507],
       [0.04478056, 0.01204282, 0.03185417],
       [0.04522626, 0.01195731, 0.03151456],
       [0.0455    , 0.01166667, 0.03135   ],
       [0.03      , 0.011957  , 0.031515  ],
       [0.02357202, 0.01064115, 0.03483618],
       [0.02769547, 0.01023282, 0.03054143],
       [0.02833333, 0.01003704, 0.02856591],
       [0.02697687, 0.01303429, 0.0385675 ],
       [0.02802451, 0.01277361, 0.03221521],
       [0.02966873, 0.01164397, 0.03211438],
       [0.037398  , 0.010652  , 0.036342  ],
       [0.032604  , 0.012396  , 0.030682  ],
       [0.034905  , 0.01154   , 0.034525  ],
       [0.030611  , 0.013039  , 0.031093  ],
       [0.034905  , 0.01154   , 0.04      ],
       [0.033742  , 0.011732  , 0.036     ],
       [0.042     , 0.012117  , 0.036     ],
       [0.041481  , 0.012651  , 0.032593  ],
       [0.

In [5]:
A.shape

(17, 3)

In [ ]:
## With the first 35 days data 
# Optimal parameters
#[0.0293013 , 0.01191042, 0.03175983]


## With the second 35 days data 
# Optimal parameters
#0.069353   0.000625  0.003858



## With the third 35 days data 
# Optimal parameters
#0.067277   0.000611  0.004702

In [ ]:
#UIUC
#0.025056   0.003858  0.008534

##Berkeley
#0.036440   0.007100  0.035057

##TexasAM
# 0.537179  , 0.053190 , 0.047984

##umich
#0.448019   0.012496  0.107455